Baekjoon/임도연/1913_달팽이.py
=> [임도연] 1주차 코드 수정

Baekjoon/이소정/1965_상자넣기.py
=> [2021.09.12] 이소정

Baekjoon/임도연/1965_상자넣기.py
=> [2021.09.12] 임도연

Baekjoon/주현이/2504_괄호의값.py
=> [2021.09.16] 주현이

Baekjoon/임도연/2504_괄호의값.py
=> [2021.09.16] 임도연

Baekjoon/임도연/21318_피아노체조.py
=> [2021.09.19] 임도연

Baekjoon/이소정/1890_점프.py, Baekjoon/이소정/self/5347_LCM.py, Baekjoon/이소정/self/README.md
=> [2021.09.23] 이소정

Baekjoon/임도연/11656_접미사배열.py, Baekjoon/임도연/1463_1로만들기.py, Baekjoon/임도연/17521_ByteCoin.py, Baekjoon/임도연/18290_NM과K.py, Baekjoon/임도연/1890_점프.py, Baekjoon/임도연/2012_등수매기기.py, Baekjoon/임도연/3273_두수의합.py, Baekjoon/임도연/5347_LCM.py
=> [2021.09.23] 임도연

Baekjoon/이소정/1660_캡틴이다솜.py, Baekjoon/이소정/README.md, Baekjoon/이소정/self/3273_두수의합.py, Baekjoon/이소정/self/README.md
=> [2021.09.26] 이소정

Baekjoon/임도연/11060_점프점프.py
=> [2021.09.30] 임도연

Baekjoon/이소정/11060_점프점프.py, Baekjoon/이소정/README.md
=> [2021.09.30] 이소정

Baekjoon/임도연/2178_미로탐색.py
=> [2021.10.03] 임도연

Baekjoon/이소정/2178_미로탐색.py, Baekjoon/이소정/README.md, Baekjoon/이소정/self/1244_스위치켜고끄기.py, Baekjoon/이소정/self/1541_잃어버린괄호.py, Baekjoon/이소정/self/README.md
=> [2021.10.03] 이소정

Baekjoon/이소정/1697_숨바꼭질.py, Baekjoon/이소정/README.md
=> [2021.10.14] 이소정

Baekjoon/임도연/1697_숨바꼭질.py, Baekjoon/임도연/9461_파도반수열.py
=> [2021.11.07] 임도연

Baekjoon/임도연/2467_용액.py
=> [2021.11.14] 임도연

Baekjoon/이소정/2467_용액.py, Baekjoon/이소정/README.md
=> [2021.11.14] 이소정

Baekjoon/임도연/19539_사과나무.py
=> [2021.12.12] 임도연

Baekjoon/임도연/1072_게임.py
=> [2021.12.16] 임도연

Baekjoon/임도연/12919_A와B2.py
=> [2021.12.19] 임도연

Baekjoon/이소정/12919_A와B2.py
=> [2021.12.19] 이소정

Baekjoon/임도연/20922_겹치는건싫어.py
=> [2021.12.23] 임도연

Baekjoon/임도연/1946_신입사원.py
=> [2021.12.26] 임도연

Baekjoon/임도연/17609_회문.py
=> [2021.12.30] 임도연

Baekjoon/임도연/7568_덩치.py
=> [2022.01.09] 임도연

Baekjoon/임도연/1012_유기농배추.py
=> [2022.01.16] 임도연

Baekjoon/이소정/1012_유기농배추.py, Baekjoon/이소정/README.md
=> [2022.01.16] 이소정

Baekjoon/임도연/11562_백양로 브레이크.py
=> [2021.01.20] 임도연

Baekjoon/이소정/11562_백양로브레이크.py, Baekjoon/이소정/README.md
11562_백양로브레이크 🔴
11562_백양로브레이크 🟡
=> [2021.01.20] 이소정

Baekjoon/임도연/2343_기타레슨.py
이진탐색의 기준이 배열의 인덱스가 아니라 값의 기준점을 잡을 수도 있다는 사실을 기억할 것을 기억하자!^^
=> [2022.01.27] 임도연

Baekjoon/이소정/1012_유기농배추.py, Baekjoon/이소정/2343_기타레슨.py, Baekjoon/이소정/README.md
=> [2022.01.27] 이소정

Baekjoon/이소정/9205_맥주마시면서걸어가기.py, Baekjoon/이소정/README.md
9205_맥주마시면서걸어가기 🟡
이게 정녕 bfs인가,,,
=> [2022.01.30] 이소정

Baekjoon/임도연/9250_맥주마시면서걸어가기.py
bfs, 탐색 문제를 좀 더 공부하도록 노력하도록 노력하자.................
=> [2022.01.30] 임도연

Baekjoon/임도연/6236_용돈관리.py
이분탐색인건 알았는데 풀지는 못해서 넘나 슬픈 것..😥
=> [2022.02.03] 임도연

Baekjoon/이소정/6236_용돈관리.py, Baekjoon/이소정/README.md
6236_용돈관리 🔴
이분탐색인줄 알았는데 왜,,,,
if문 조건 중요해..!
=> [2022.02.03] 이소정

Baekjoon/임도연/2304_창고다각형.py
=> [2022.02.06] 임도연

Baekjoon/이소정/2304_창고다각형.py, Baekjoon/이소정/README.md
=> [2022.02.06] 이소정

Baekjoon/임도연/3184_양.py
dfs는 자신있는데 bfs는 아직도 모르겠는 나
아무튼 dfs로 풀리면 상관없다 이말이야
=> [2022.02.10] 임도연

Baekjoon/이소정/3184_양.py, Baekjoon/이소정/README.md
=> [2022.02.10] 이소정

Baekjoon/이소정/9465_스티커.py, Baekjoon/이소정/README.md
=> [2022.02.21] 이소정

Baekjoon/임도연/9465_스티커.py
=> [2022.02.21] 임도연

Baekjoon/임도연/10844_쉬운계단수.py
=> [2022.03.10] 임도연

Baekjoon/임도연/15990_123더하기5.py
나는 언제쯤 뇌가 정상적으로 돌아서 문제보고 풀이방식을 깨달을 수 있을까? 푸하하하하하
=> [2022.04.14] 임도연

Baekjoon/임도연/14501_퇴사.py, Baekjoon/임도연/16171_나는친구가적다(small).py
=> [2022.04.21] 임도연

Baekjoon/이소정/14501_퇴사.py, Baekjoon/이소정/README.md
14501_퇴사🔴
입사도 안했는데 퇴사라니ㅠㅠ dp는 어려웡
=> [2022.04.21] 이소정

Baekjoon/이소정/21608_상어초등학교.py, Baekjoon/이소정/README.md
=> [2022.05.02] 이소정

Baekjoon/임도연/1780_종이의개수.py
=> [2022.05.13] 임도연

Baekjoon/임도연/14503_로봇청소기.py
=> [2022.05.15] 임도연

Baekjoon/이소정/1780_종이의개수.py, Baekjoon/이소정/README.md
=> [2022.05.13] 이소정

Baekjoon/이소정/15685_드래곤커브.py, Baekjoon/이소정/README.md
=> [2022.06.06] 이소정

Baekjoon/임도연/10026_적록색약.py
=> [2022.06.12] 임도연

Baekjoon/이소정/10026_적록색약.py, Baekjoon/이소정/README.md
10026_적록색약 🟡
dfs는 어려워,,, 런타임에러 극뽁!!
=> [2022.06.12] 이소정

Baekjoon/임도연/14728_벼락치기.py
knapsack problem 확실하게 이해할 것..
나만 모르는 유명한 유형 억울함 말 안돼 다음에는 맞출거임 진짜
=> [2022.06.20] 임도연

Baekjoon/이소정/14728_벼락치기.py, Baekjoon/이소정/README.md
14728_벼락치기 🔴
이 문제유형 유명해진거 나한테만 비밀이었나~? 어이없네~
=> [2022.06.20] 이소정

Baekjoon/임도연/1874_스택수열.py
=> [2022.06.26] 임도연

Baekjoon/이소정/1874_스택수열.py, Baekjoon/이소정/README.md
=> [2022.06.26] 이소정
